# Generated by Django 4.2.7 on 2023-12-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_interestclub_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture",
            name="course",
        ),
        migrations.AddField(
            model_name="course",
            name="lectures",
            field=models.ManyToManyField(null=True, to="main.lecture"),
        ),
    ]
