# Generated by Django 4.2.7 on 2023-12-26 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_lecture_course_course_lectures"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("file", models.FileField(null=True, upload_to="task/")),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="hometask",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.hometask",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.hometask",
            ),
        ),
    ]
