# Generated by Django 4.2.7 on 2023-12-27 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_hometask_assignment_hometask_lecture_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="title",
        ),
        migrations.AddField(
            model_name="assignment",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.student",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
