# Generated by Django 4.2.7 on 2023-12-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_assignment_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="bio",
        ),
    ]
