# Generated by Django 4.2.7 on 2023-12-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_teacher_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
