# Generated by Django 4.2.7 on 2023-12-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_student_type_teacher_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="clubs_in",
            field=models.ManyToManyField(to="main.interestclub"),
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
