# Generated by Django 4.2.10 on 2024-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_student_clubs_in_delete_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="clubs_in",
            field=models.ManyToManyField(null=True, to="main.interestclub"),
        ),
    ]
