# Generated by Django 4.2.10 on 2024-02-28 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_student_clubs_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.course",
            ),
        ),
    ]
