# Generated by Django 4.2.10 on 2024-02-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_group_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="course",
        ),
        migrations.AddField(
            model_name="group",
            name="course",
            field=models.ManyToManyField(null=True, to="main.course"),
        ),
    ]
