# Generated by Django 4.2.10 on 2024-03-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_hometask_date_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hometask",
            name="file",
        ),
    ]
